spring:
  profiles:
    active: qa_common,start,h2_db

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  redis:
    database: 0
    host: 127.0.0.1
    port: 10016
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
