spring:
  datasource:
    url: jdbc:h2:file:/data/mxz;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
    schema:
      - classpath:db/schema.sql
    data:
      - classpath:db/data.sql
#配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: 'false'
#    show-sql: 'true'
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: true
        web-allow-others: true

#mybatis:
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml